"""Prometheus metrics for ContextFlow — a read-only observability seam.

Design constraints (do NOT change app behaviour):
  * Business metrics (users, workspaces, repositories, semantic cache,
    AI/token counts) are GAUGES sampled from the DB at scrape time by a
    custom collector — there are no counters to increment in hot paths,
    so the chat/auth/RBAC code is untouched.
  * The only per-request hooks are a start-timer / observe-duration pair
    for HTTP latency; both are wrapped so they can never break a request.

Exposure: GET /metrics is served by the same app but gated by
METRICS_TOKEN (Bearer) when that env var is set, so the public Traefik
ingress can't read it. Prometheus scrapes it with the token; the
Prometheus and Grafana UIs themselves are ClusterIP-only. See
docs/MONITORING.md.
"""
import os
import time

from flask import request, Response, g
from prometheus_client import (CollectorRegistry, Counter, Histogram,
                               generate_latest, CONTENT_TYPE_LATEST)
from prometheus_client.core import GaugeMetricFamily
from sqlalchemy import func

from app.models import (db, User, Company, Workspace, KnowledgeSource,
                        Document, Chunk, Capsule, Message, SemanticCacheEntry)

# Private registry: only ContextFlow series, no default process/GC noise.
REGISTRY = CollectorRegistry()

HTTP_REQUESTS = Counter(
    "contextflow_http_requests_total", "HTTP requests handled",
    ["method", "endpoint", "status"], registry=REGISTRY)
HTTP_LATENCY = Histogram(
    "contextflow_http_request_duration_seconds", "HTTP request latency (s)",
    ["method", "endpoint"], registry=REGISTRY)


class ContextFlowCollector:
    """Sampled once per scrape: a handful of COUNT/SUM queries turned into
    gauges. Read-only; any failure yields nothing rather than erroring the
    endpoint (Prometheus records the target as up with fewer series)."""

    def collect(self):
        try:
            samples = self._sample()
        except Exception:
            db.session.rollback()
            return
        for name, doc, value in samples:
            yield GaugeMetricFamily(name, doc, value=float(value))

    def _sample(self):
        assistant = Message.query.filter(Message.role == "assistant")
        hits = assistant.filter(Message.cache_hit.is_(True)).count()
        # A generation (tokens produced) is exactly a cache miss that went
        # to the model; greetings and cache hits produce 0 output tokens.
        misses = assistant.filter(Message.tokens_out > 0).count()
        ti, to = (db.session.query(
                    func.coalesce(func.sum(Message.tokens_in), 0),
                    func.coalesce(func.sum(Message.tokens_out), 0))
                  .filter(Message.role == "assistant").one())
        avg_ms = (db.session.query(func.coalesce(func.avg(Message.response_ms), 0))
                  .filter(Message.role == "assistant").scalar()) or 0

        gh = KnowledgeSource.query.filter(KnowledgeSource.type == "github")
        repos = gh.count()
        repos_indexed = (db.session.query(
                            func.count(func.distinct(Document.source_id)))
                         .join(KnowledgeSource,
                               Document.source_id == KnowledgeSource.id)
                         .filter(KnowledgeSource.type == "github").scalar()) or 0
        embedded = Chunk.query.filter(Chunk.embedding.isnot(None)).count()

        return [
            # Entities
            ("contextflow_users_total", "Registered users", User.query.count()),
            ("contextflow_companies_total", "Companies", Company.query.count()),
            ("contextflow_workspaces_total", "Workspaces", Workspace.query.count()),
            # Repository Inventory
            ("contextflow_repositories_total", "Connected GitHub repositories", repos),
            ("contextflow_repositories_indexed", "Repositories with >=1 indexed document", repos_indexed),
            ("contextflow_documents_total", "Indexed documents", Document.query.count()),
            ("contextflow_chunks_total", "Retrieval chunks", Chunk.query.count()),
            ("contextflow_chunks_embedded", "Chunks with an embedding", embedded),
            ("contextflow_knowledge_index_total", "Knowledge Index entries (capsules)", Capsule.query.count()),
            # Semantic cache
            ("contextflow_semantic_cache_entries", "Live semantic-cache entries", SemanticCacheEntry.query.count()),
            ("contextflow_semantic_cache_hits_total", "Answers served from the semantic cache", hits),
            ("contextflow_semantic_cache_misses_total", "Answers generated by the model (cache misses)", misses),
            # AI / tokens / latency
            ("contextflow_ai_answers_total", "Assistant answers (hits + generations + greetings)", assistant.count()),
            ("contextflow_tokens_in_total", "Prompt tokens consumed", int(ti)),
            ("contextflow_tokens_out_total", "Completion tokens produced", int(to)),
            ("contextflow_response_ms_avg", "Mean assistant response time (ms)", float(avg_ms)),
        ]


_initialised = False


def init_metrics(app):
    """Register the /metrics endpoint, the request-timing hooks and the DB
    collector. Idempotent — safe if imported more than once."""
    global _initialised
    if _initialised:
        return
    _initialised = True
    REGISTRY.register(ContextFlowCollector())

    @app.before_request
    def _metrics_start_timer():
        g._metrics_t0 = time.perf_counter()

    @app.after_request
    def _metrics_observe(response):
        try:
            if request.path != "/metrics":
                dur = time.perf_counter() - getattr(g, "_metrics_t0",
                                                    time.perf_counter())
                endpoint = request.endpoint or "unknown"
                HTTP_REQUESTS.labels(request.method, endpoint,
                                     response.status_code).inc()
                HTTP_LATENCY.labels(request.method, endpoint).observe(dur)
        except Exception:
            pass  # metrics must never break a real response
        return response

    @app.route("/metrics")
    def metrics():
        # Token gate: when METRICS_TOKEN is set (production), only a caller
        # presenting it (Prometheus) may read metrics — the public ingress
        # gets 403. Unset (local dev) leaves it open.
        token = os.getenv("METRICS_TOKEN")
        if token and request.headers.get("Authorization") != f"Bearer {token}":
            return Response("forbidden\n", status=403, mimetype="text/plain")
        return Response(generate_latest(REGISTRY), mimetype=CONTENT_TYPE_LATEST)
