"""message capsule-routing snapshot and token accounting

Revision ID: b9ca357d28c4
Revises: c9035f63884b
Create Date: 2026-07-07 04:42:24.803755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ca357d28c4'
down_revision = 'c9035f63884b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default on the NOT NULL integers so existing rows backfill
    # to 0 (SQLite rejects a NOT NULL add without one).
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capsules_used', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('capsules_withheld', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('chunks_used', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('context_tokens', sa.Integer(),
                                      nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('naive_tokens', sa.Integer(),
                                      nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('naive_tokens')
        batch_op.drop_column('context_tokens')
        batch_op.drop_column('chunks_used')
        batch_op.drop_column('capsules_withheld')
        batch_op.drop_column('capsules_used')

    # ### end Alembic commands ###
