"""document extraction fields: storage_key, text, meta, error

Revision ID: c9035f63884b
Revises: ebf2d8398bd5
Create Date: 2026-07-07 01:57:33.029997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9035f63884b'
down_revision = 'ebf2d8398bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('meta')
        batch_op.drop_column('text')
        batch_op.drop_column('storage_key')

    # ### end Alembic commands ###
