"""knowledge foundations: sources, documents, chunks, capsules

Creates the v2 knowledge tables and moves each workspace's GitHub
connection (repo_url / discovered_context / last_scanned_at) into a
knowledge_source row of type "github". The data-copy step only matters
for existing dev SQLite databases — fresh installs and the future
Postgres migration start empty above the baseline.

Revision ID: ebf2d8398bd5
Revises: 8a58d8a4a68e
Create Date: 2026-07-07 01:20:37.039055

"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ebf2d8398bd5'
down_revision = '8a58d8a4a68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capsule',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('related', sa.JSON(), nullable=False),
    sa.Column('centroid', sa.LargeBinary(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug')
    )
    with op.batch_alter_table('capsule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capsule_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('knowledge_source',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('uri', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'uri')
    )
    op.create_table('document',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_source.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'sha256')
    )
    op.create_table('chunk',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunk_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('capsule_chunk',
    sa.Column('capsule_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsule.id'], ),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunk.id'], ),
    sa.PrimaryKeyConstraint('capsule_id', 'chunk_id')
    )
    # ── Data migration: each v1 workspace becomes workspace + one
    # github knowledge_source, before the old columns are dropped.
    bind = op.get_bind()
    rows = bind.execute(sa.text(
        "SELECT id, name, repo_url, discovered_context, last_scanned_at, "
        "created_at FROM workspace")).mappings().all()
    for r in rows:
        bind.execute(sa.text(
            "INSERT INTO knowledge_source (id, workspace_id, type, name, "
            "uri, status, profile, error, created_at, last_ingested_at) "
            "VALUES (:id, :ws, 'github', :name, :uri, 'ready', :profile, "
            "NULL, :created, :ingested)"),
            {"id": uuid.uuid4().hex, "ws": r["id"], "name": r["name"],
             "uri": r["repo_url"], "profile": r["discovered_context"],
             "created": r["created_at"], "ingested": r["last_scanned_at"]})

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.drop_column('last_scanned_at')
        batch_op.drop_column('discovered_context')
        batch_op.drop_column('repo_url')

    # ### end Alembic commands ###


def downgrade():
    # Columns come back nullable first, get backfilled from the github
    # source rows, then tighten to the original NOT NULL. A workspace
    # with no github source (possible after Increment 2) downgrades
    # with an empty repo_url — v1 has no concept of it; lossy by nature.
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repo_url', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('discovered_context', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('last_scanned_at', sa.DATETIME(), nullable=True))

    bind = op.get_bind()
    bind.execute(sa.text(
        "UPDATE workspace SET "
        "repo_url = COALESCE((SELECT k.uri FROM knowledge_source k "
        "  WHERE k.workspace_id = workspace.id AND k.type = 'github'), ''), "
        "discovered_context = COALESCE((SELECT k.profile FROM knowledge_source k "
        "  WHERE k.workspace_id = workspace.id AND k.type = 'github'), '{}'), "
        "last_scanned_at = (SELECT k.last_ingested_at FROM knowledge_source k "
        "  WHERE k.workspace_id = workspace.id AND k.type = 'github')"))

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column('repo_url', nullable=False,
                              existing_type=sa.VARCHAR(length=300))
        batch_op.alter_column('discovered_context', nullable=False,
                              existing_type=sqlite.JSON())

    op.drop_table('capsule_chunk')
    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunk_workspace_id'))

    op.drop_table('chunk')
    op.drop_table('document')
    op.drop_table('knowledge_source')
    with op.batch_alter_table('capsule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capsule_workspace_id'))

    op.drop_table('capsule')
    # ### end Alembic commands ###
